
/**************************************************************/
/*                                                            */
/*      Copyright Mentor Graphics Corporation 2006 - 2012     */
/*                  All Rights Reserved                       */
/*                                                            */
/*       THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY      */
/*         INFORMATION WHICH IS THE PROPERTY OF MENTOR        */
/*         GRAPHICS CORPORATION OR ITS LICENSORS AND IS       */
/*                 SUBJECT TO LICENSE TERMS.                  */
/*                                                            */
/**************************************************************/

//*<
//* Generated By Model Builder, Mentor Graphics Computer Systems, Inc.
//*
//* This file is write protected. 
//* DO NOT MODIFY THIS FILE.
//*
//* This file is generated according to the parameters in the 
//* Model Builder form.
//* This class contains the infrastructure to define the behavior of the component.
//* The driver_pv will be derived from this class.
//*
//* Model Builder version: 4.1.0
//* Generated on: Jan. 27, 2016 03:09:19 PM, (user: mbradley)
//*>


#include "driver_model.h"

#ifdef MODEL_BUILDER_VERSION_NUMBER
#if 4100 != MODEL_BUILDER_VERSION_NUMBER
#error "This model was generated using Model Builder version: 4.1.0. Please regenerate model."
#endif
#else
#error "Please regenerate model."
#endif

using namespace sc_core;
using namespace sc_dt;
using namespace std;


driver_pv_base::driver_pv_base(sc_module_name& module_name) : 
  driver_pv_base_mb_compatibility(module_name),
  driver_pv_base_parameters(this),
  VISTA_MB_PV_INIT_MEMBER(master),
  VISTA_MB_PV_INIT_MEMBER(irq) {


  payload_on_stack = 0;
  payload_for_token = 0;

  irq.register_cb(this, &self::cb_signal_irq);
  VISTA_MB_PV_BIND_BW_PROCESS_TO_MASTER(master);
  VISTA_MB_PV_REGISTER_SELF_BW_PROCESS_CALLBACKS(master);

}

void driver_pv_base::reset_model() {
  // reset all registers


  
  // reset value for output signals

  // reset value for input signals

}

driver_pv_base_parameters::driver_pv_base_parameters(sc_object* object) :
  m_object(object),
  SD_INITIALIZE_PARAMETER_EXTERNALLY(object, clock, sc_core::sc_time(10, sc_core::SC_NS)),
  SD_INITIALIZE_PARAMETER_EXTERNALLY(object, signal_clock, clock),
  SD_INITIALIZE_PARAMETER_EXTERNALLY(object, axi_clock, clock),
  SD_INITIALIZE_PARAMETER_EXTERNALLY(object, nominal_voltage, 1),
  SD_INITIALIZE_PARAMETER_EXTERNALLY(object, mb_debug, false),
  SD_INITIALIZE_PARAMETER_EXTERNALLY(object, verbose_parameters, true),
  SD_INITIALIZE_PARAMETER_EXTERNALLY(object, dmi_enabled, true),
  SD_INITIALIZE_PARAMETER_EXTERNALLY(object, warning_level, "WARNING"),
  SD_INITIALIZE_PARAMETER_EXTERNALLY(object, master_outstanding, 1),
  SD_INITIALIZE_PARAMETER_EXTERNALLY(object, master_read_data_queue_size, 0),
  SD_INITIALIZE_PARAMETER_EXTERNALLY(object, master_write_data_queue_size, 0),
  SD_INITIALIZE_PARAMETER_EXTERNALLY(object, irq_pipeline_length, 2)
{
  if(verbose_parameters) print_parameters();
}

void driver_pv_base_parameters::print_parameters()
{
  const char* name;
  if (!strcmp(m_object->basename(), "PV"))
    name = m_object->get_parent()->name();
  else
    name = m_object->name();

  std::cout.setf(ios::hex, ios::basefield);
  std::cout.setf(ios::showbase);
  std::cout << name << "::parameters:\n";
  std::cout << "\tclock = " << clock << "\n";
  std::cout << "\tsignal_clock = " << signal_clock << "\n";
  std::cout << "\taxi_clock = " << axi_clock << "\n";
  std::cout << "\tnominal_voltage = " << nominal_voltage << "\n";
  std::cout << "\tmb_debug = " << mb_debug << "\n";
  std::cout << "\tverbose_parameters = " << verbose_parameters << "\n";
  std::cout << "\tdmi_enabled = " << dmi_enabled << "\n";
  std::cout << "\twarning_level = " << warning_level << "\n";
  std::cout << "\tmaster_outstanding = " << master_outstanding << "\n";
  std::cout << "\tmaster_read_data_queue_size = " << master_read_data_queue_size << "\n";
  std::cout << "\tmaster_write_data_queue_size = " << master_write_data_queue_size << "\n";
  std::cout << "\tirq_pipeline_length = " << irq_pipeline_length << "\n";
  std::cout.unsetf(ios::showbase);
  std::cout.setf(ios::dec, ios::basefield);
  std::cout << std::endl;
}



/**************************************************************/
/*                                                            */
/*      Copyright Mentor Graphics Corporation 2006 - 2012     */
/*                  All Rights Reserved                       */
/*                                                            */
/*       THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY      */
/*         INFORMATION WHICH IS THE PROPERTY OF MENTOR        */
/*         GRAPHICS CORPORATION OR ITS LICENSORS AND IS       */
/*                 SUBJECT TO LICENSE TERMS.                  */
/*                                                            */
/**************************************************************/

//*<
//* Generated By Model Builder, Mentor Graphics Computer Systems, Inc.
//*
//* This file is write protected.
//* DO NOT MODIFY THIS FILE.
//*
//* This file is used only for learning the component.
//* It contains the machine architecture class for your driver model.
//* 
//* Model Builder version: 4.1.0
//* Generated on: Jan. 27, 2016 03:09:20 PM, (user: mbradley)
//*>

#include "driver_model.h"
#include "model_builder.h"

using namespace ::mb::utl::minmax;

driver_machine_arch::driver_machine_arch()
    : MachineArch(2, 0) {
        reset();
    }
    
    ////////////////////////////////////////////////////////////////////
    //   function for port: master
    ////////////////////////////////////////////////////////////////////
    
    
    //////
    // functions for port: master, transaction: WRITE
    //////
    
    void driver_machine_arch::transaction_instance__master__WRITE
      (
        sc_dt::uint64 _address,
        sc_dt::uint64 _size,
        sc_dt::uint64 _data, 
        bool has_been_error, 
        sc_dt::uint64 currentTime
      )
    {
      
    }
    
    //////
    // functions for port: master, transaction: READ
    //////
    
    void driver_machine_arch::transaction_instance__master__READ
      (
        sc_dt::uint64 _address,
        sc_dt::uint64 _size,
        sc_dt::uint64 _data, 
        bool has_been_error, 
        sc_dt::uint64 currentTime
      )
    {
      
    }
    
    ////////////////////////////////////////////////////////////////////
    //   function for port: irq
    ////////////////////////////////////////////////////////////////////
    
    
    //////
    // functions for port: irq, transaction: WRITE
    //////
    
    void driver_machine_arch::transaction_instance__irq__WRITE
      (
        sc_dt::uint64 _address,
        sc_dt::uint64 _size,
        sc_dt::uint64 _data, 
        bool has_been_error, 
        sc_dt::uint64 currentTime
      )
    {
      
    }

void driver_machine_arch::startTransaction(unsigned portIndex, unsigned transactionIndex, sc_dt::uint64 currentTime) {
  switch(portIndex) {
    case(0) : break;
    case(1) : break;
    default: break;
  }
}
VariableBase* driver_machine_arch::getVariableBasePtrByName(const char* name) {
  return NULL;
}
Register* driver_machine_arch::getRegisterByName(const char* name) {
  return 0;
}
void driver_machine_arch::reset() { 
    MachineArch::reset();
}
bool driver_machine_arch::getAddressRange(unsigned portIndex, sc_dt::uint64& begin, sc_dt::uint64& end) {
    switch(portIndex) {
        case(0) :   return false;
        case(1) :   return false;
        default: break;
    }
    return false; 
}
void driver_machine_arch::callTransaction(unsigned portIndex, unsigned transactionIndex, sc_dt::uint64 address, sc_dt::uint64 size, sc_dt::uint64 data, bool has_been_error, sc_dt::uint64 currentTime) {
    switch(portIndex) {
        case(0) : { //port: master
            switch(transactionIndex) {
                case(0) : { //transaction: WRITE
                    this->transaction_instance__master__WRITE
                      (
                        address, 
                        size, 
                        data, 
                        has_been_error, 
                        currentTime
                      );
                    break;
                }
                case(1) : { //transaction: READ
                    this->transaction_instance__master__READ
                      (
                        address, 
                        size, 
                        data, 
                        has_been_error, 
                        currentTime
                      );
                    break;
                }
            }
            break;
        }
        case(1) : { //port: irq
            switch(transactionIndex) {
                case(0) : { //transaction: WRITE
                    this->transaction_instance__irq__WRITE
                      (
                        address, 
                        size, 
                        data, 
                        has_been_error, 
                        currentTime
                      );
                    break;
                }
            }
            break;
        }
        default: break;
    }
}


/**************************************************************/
/*                                                            */
/*      Copyright Mentor Graphics Corporation 2006 - 2012     */
/*                  All Rights Reserved                       */
/*                                                            */
/*       THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY      */
/*         INFORMATION WHICH IS THE PROPERTY OF MENTOR        */
/*         GRAPHICS CORPORATION OR ITS LICENSORS AND IS       */
/*                 SUBJECT TO LICENSE TERMS.                  */
/*                                                            */
/**************************************************************/

//*<
//* Generated By Model Builder, Mentor Graphics Computer Systems, Inc.
//*
//* This file is write protected. 
//* DO NOT MODIFY THIS FILE.
//*
//* This file is generated according to the parameters in the 
//* Model Builder form.
//* 
//* Any change in parameters, policies, ports, protocols, etc. will change this file
//* upon generation of the timing model (using generate_timing_model command).
//* The driver_t will be derived from this class.
//*
//* Model Builder version: 4.1.0
//* Generated on: Jan. 27, 2016 03:09:20 PM, (user: mbradley)
//*>




#include "driver_model.h"
#include <math.h>
#include <stdlib.h>

using namespace esl::tlm_sim;
using namespace esl::sc_sim;
using namespace std;
using namespace sc_dt;
using namespace sc_core;


void driver_t_base::schedule_axi_READ
(long port_index,
 sc_dt::uint64 delay,
 long& transactionSize,
 esl::include::transaction_power& power , long TR_ID, long ARADDR, long* RDATA, long ARSIZE, long block_size, long ARBURST, long ARLEN, long ARLOCK) {
  sc_dt::uint64 local_address = 0;
  local_address = ARADDR,
  scheduleGenericTransaction(port_index,
                             0,
                             local_address,
                             (unsigned char*)RDATA,
                             transactionSize,
                             block_size,
                             0, papoulis::getSimulationTime() + delay,
                             0,
                             0);
}

void driver_t_base::schedule_axi_WRITE
(long port_index,
 sc_dt::uint64 delay,
 long& transactionSize,
 esl::include::transaction_power& power , long TR_ID, long AWADDR, long* WDATA, long AWSIZE, long block_size, long AWBURST, long AWLEN, long AWLOCK) {
  sc_dt::uint64 local_address = 0;
  local_address = AWADDR,
  scheduleGenericTransaction(port_index,
                             1,
                             local_address,
                             (unsigned char*)WDATA,
                             transactionSize,
                             block_size,
                             0, papoulis::getSimulationTime() + delay,
                             0,
                             0);
}



void driver_t_base::start_transaction_axi_READ
(esl::include::TRequest* request,
 unsigned port_index,
 sc_dt::uint64 startTime,
 sc_dt::uint64 endTime,
 sc_dt::uint64* parameters,
 bool hasBeenError) {
  
  long burstSize = request->getSize();
  parameters[1] = request->getAddress();
  parameters[2] = request->getFirstDataBlock();
  parameters[4] = request->getBlockSize();
  
  this->getMachineArch()->startTransaction(port_index,
                                           1,
                                           startTime);
  
  this->accept_axi_READ
    (port_index, 
     startTime, 
     burstSize, 
     parameters[0], 
     parameters[1], 
     parameters[2], 
     parameters[3], 
     parameters[4], 
     parameters[5], 
     parameters[6], 
     parameters[7]);
}

void driver_t_base::end_transaction_axi_READ
(esl::include::TRequest* request,
 unsigned port_index,
 sc_dt::uint64 startTime,
 sc_dt::uint64 endTime,
 sc_dt::uint64* parameters,
 bool hasBeenError) {
  long burstSize = request->getSize();
  parameters[1] = request->getAddress();
  parameters[2] = request->getFirstDataBlock();
  parameters[4] = request->getBlockSize();                                                                         
  this->getMachineArch()->callTransaction(port_index, 
                                          1, 
                                          request->getAddress(),
                                          burstSize,
                                          request->getFirstDataBlock(),
                                          hasBeenError,
                                          startTime);
  
  this->end_axi_READ
    (port_index,
     endTime,
     burstSize,
     parameters[0],
     parameters[1],
     parameters[2],
     parameters[3],
     parameters[4],
     parameters[5],
     parameters[6],
     parameters[7]);
}
void driver_t_base::start_transaction_axi_WRITE
(esl::include::TRequest* request,
 unsigned port_index,
 sc_dt::uint64 startTime,
 sc_dt::uint64 endTime,
 sc_dt::uint64* parameters,
 bool hasBeenError) {
  
  long burstSize = request->getSize();
  parameters[1] = request->getAddress();
  parameters[2] = request->getFirstDataBlock();
  parameters[4] = request->getBlockSize();
  
  this->getMachineArch()->startTransaction(port_index,
                                           0,
                                           startTime);
  
  this->accept_axi_WRITE
    (port_index, 
     startTime, 
     burstSize, 
     parameters[0], 
     parameters[1], 
     parameters[2], 
     parameters[3], 
     parameters[4], 
     parameters[5], 
     parameters[6], 
     parameters[7]);
}

void driver_t_base::end_transaction_axi_WRITE
(esl::include::TRequest* request,
 unsigned port_index,
 sc_dt::uint64 startTime,
 sc_dt::uint64 endTime,
 sc_dt::uint64* parameters,
 bool hasBeenError) {
  long burstSize = request->getSize();
  parameters[1] = request->getAddress();
  parameters[2] = request->getFirstDataBlock();
  parameters[4] = request->getBlockSize();                                                                         
  this->getMachineArch()->callTransaction(port_index, 
                                          0, 
                                          request->getAddress(),
                                          burstSize,
                                          request->getFirstDataBlock(),
                                          hasBeenError,
                                          startTime);
  
  this->end_axi_WRITE
    (port_index,
     endTime,
     burstSize,
     parameters[0],
     parameters[1],
     parameters[2],
     parameters[3],
     parameters[4],
     parameters[5],
     parameters[6],
     parameters[7]);
}
void driver_t_base::start_transaction_signal_WRITE
(esl::include::TRequest* request,
 unsigned port_index,
 sc_dt::uint64 startTime,
 sc_dt::uint64 endTime,
 sc_dt::uint64* parameters,
 bool hasBeenError) {
  
  long burstSize = request->getSize();
  parameters[0] = request->getAddress();
  parameters[1] = request->getFirstDataBlock();
  parameters[2] = request->getBlockSize();
  
  this->getMachineArch()->startTransaction(port_index,
                                           0,
                                           startTime);
  
  this->accept_signal_WRITE
    (port_index, 
     startTime, 
     burstSize, 
     parameters[0], 
     parameters[1], 
     parameters[2]);
}

void driver_t_base::end_transaction_signal_WRITE
(esl::include::TRequest* request,
 unsigned port_index,
 sc_dt::uint64 startTime,
 sc_dt::uint64 endTime,
 sc_dt::uint64* parameters,
 bool hasBeenError) {
  long burstSize = request->getSize();
  parameters[0] = request->getAddress();
  parameters[1] = request->getFirstDataBlock();
  parameters[2] = request->getBlockSize();                                                                         
  this->getMachineArch()->callTransaction(port_index, 
                                          0, 
                                          request->getAddress(),
                                          burstSize,
                                          request->getFirstDataBlock(),
                                          hasBeenError,
                                          startTime);
  
  this->end_signal_WRITE
    (port_index,
     endTime,
     burstSize,
     parameters[0],
     parameters[1],
     parameters[2]);
}

driver_t_base::TransactionCallbackFunctionPointer driver_t_base::getTransactionCallback(unsigned callbackIndex) {
  static TransactionCallbackFunctionPointer funcArray[] = {
    static_cast<TransactionCallbackFunctionPointer>(&driver_t_base::start_transaction_axi_READ),
    static_cast<TransactionCallbackFunctionPointer>(&driver_t_base::start_transaction_axi_WRITE),
    static_cast<TransactionCallbackFunctionPointer>(&driver_t_base::null_transaction_callback),
    static_cast<TransactionCallbackFunctionPointer>(&driver_t_base::start_transaction_signal_WRITE),
    static_cast<TransactionCallbackFunctionPointer>(&driver_t_base::end_transaction_axi_READ),
    static_cast<TransactionCallbackFunctionPointer>(&driver_t_base::end_transaction_axi_WRITE),
    static_cast<TransactionCallbackFunctionPointer>(&driver_t_base::null_transaction_callback),
    static_cast<TransactionCallbackFunctionPointer>(&driver_t_base::end_transaction_signal_WRITE),
    0
  };
  if(callbackIndex >= sizeof(funcArray) / sizeof(*funcArray) - 1)
    return 0;
  return funcArray[callbackIndex];
}

config::real80 driver_t_base::get_state_power() { 
  config::real80 power_value = 0;

  

  return power_value;
}

driver_t_base::driver_t_base(sc_module_name& module_name, long simulation) :
  papoulis::SystemCBaseModel(module_name),
  m_machineArch(new driver_machine_arch()),
  SD_INITIALIZE_PARAMETER(clock, sc_core::sc_time(10, sc_core::SC_NS)),
  SD_INITIALIZE_PARAMETER(signal_clock, clock),
  SD_INITIALIZE_PARAMETER(axi_clock, clock),
  SD_INITIALIZE_PARAMETER(nominal_voltage, 1),
  SD_INITIALIZE_PARAMETER(mb_debug, false),
  SD_INITIALIZE_PARAMETER(verbose_parameters, true),
  SD_INITIALIZE_PARAMETER(dmi_enabled, true),
  SD_INITIALIZE_PARAMETER(warning_level, "WARNING"),
  SD_INITIALIZE_PARAMETER(master_outstanding, 1),
  SD_INITIALIZE_PARAMETER(master_read_data_queue_size, 0),
  SD_INITIALIZE_PARAMETER(master_write_data_queue_size, 0),
  SD_INITIALIZE_PARAMETER(irq_pipeline_length, 2),
  m_simulation(simulation)
{
  bool separate_read_channel = false;
  bool separate_write_channel = false;
  fix_clock_parameter(axi_clock, "axi_clock");
  separate_read_channel = false;
  separate_write_channel = false;
  port_descriptions[master].port_name = "master";
  separate_read_channel = true;
  port_descriptions[master].port_kind = PortDescription::READ_CHANNEL_PORT;
  separate_write_channel = true;
  port_descriptions[master].port_kind = PortDescription::WRITE_CHANNEL_PORT;
  if (separate_write_channel && separate_read_channel)
    port_descriptions[master].port_kind = PortDescription::SEPARATE_READ_WRIE_CHANNEL_PORT;
  port_descriptions[master].is_read_write_address_channel = 0;
  
  port_descriptions[master].is_master_port = 1;
  port_descriptions[master].is_signal_port = 0;
  port_descriptions[master].port_width = ((32 + 7) >> 3);
  port_descriptions[master].port_width_in_bits = 32;
  port_descriptions[master].protocol_name = "axi";
  port_descriptions[master].ipxactBusDef.vendor = "amba.com";
  port_descriptions[master].ipxactBusDef.library = "AMBA3";
  port_descriptions[master].ipxactBusDef.name = "AXI";
  port_descriptions[master].ipxactBusDef.version = "r1p0_5"; 
  port_descriptions[master].ipxactAbstrDef.vendor = "Mentor.com";
  port_descriptions[master].ipxactAbstrDef.library = "Lib_ipxact";
  port_descriptions[master].ipxactAbstrDef.name = "AXI_tlm20";
  port_descriptions[master].ipxactAbstrDef.version = "1.0";
  port_descriptions[master].port_must_bind = 1;
  port_descriptions[master].params_count = 8;
  if (master_outstanding == 0) {
    master_outstanding = 1;
    printf("WARNING: in \"%s\" the \"master_outstanding\" parameter is 0, a default value of 1 is used\n", name());
  }
  port_descriptions[master].pending = master_outstanding;
  port_descriptions[master].read_data_queue_size = master_read_data_queue_size;
  port_descriptions[master].write_data_queue_size = master_write_data_queue_size;
  port_descriptions[master].clock = axi_clock;
  m_machineArch->configureClock(master, mb::sysc::sc_time_to_ps(axi_clock));
  port_descriptions[master].add_read_phase(tlm::tlm_phase(tlm::BEGIN_REQ), !1, 0);
  port_descriptions[master].add_read_phase(tlm::tlm_phase(tlm::END_REQ), !0, 0);
  port_descriptions[master].add_read_phase(tlm::tlm_phase(tlm::BEGIN_RESP), !0, 1);
  port_descriptions[master].add_read_phase(tlm::tlm_phase(tlm::END_RESP), !1, 1);
  port_descriptions[master].add_write_phase(tlm::tlm_phase(tlm::BEGIN_REQ), !1, 0);
  port_descriptions[master].add_write_phase(tlm::tlm_phase(tlm::END_REQ), !0, 0);
  port_descriptions[master].add_write_phase(tlm::tlm_phase(tlm::BEGIN_RESP), !0, 1);
  port_descriptions[master].add_write_phase(tlm::tlm_phase(tlm::END_RESP), !1, 1);

  fix_clock_parameter(signal_clock, "signal_clock");
  separate_read_channel = false;
  separate_write_channel = false;
  port_descriptions[irq].port_name = "irq";
  separate_write_channel = true;
  port_descriptions[irq].port_kind = PortDescription::WRITE_CHANNEL_PORT;
  if (separate_write_channel && separate_read_channel)
    port_descriptions[irq].port_kind = PortDescription::SEPARATE_READ_WRIE_CHANNEL_PORT;
  port_descriptions[irq].is_read_write_address_channel = 0;
  
  port_descriptions[irq].is_master_port = 0;
  port_descriptions[irq].is_signal_port = 1;
  port_descriptions[irq].port_width = ((1 + 7) >> 3);
  port_descriptions[irq].port_width_in_bits = 1;
  port_descriptions[irq].protocol_name = "signal";
  port_descriptions[irq].ipxactBusDef.vendor = "Mentor.com";
  port_descriptions[irq].ipxactBusDef.library = "Lib_ipxact";
  port_descriptions[irq].ipxactBusDef.name = "signal";
  port_descriptions[irq].ipxactBusDef.version = "1.0"; 
  port_descriptions[irq].ipxactAbstrDef.vendor = "Mentor.com";
  port_descriptions[irq].ipxactAbstrDef.library = "Lib_ipxact";
  port_descriptions[irq].ipxactAbstrDef.name = "signal_tlm20";
  port_descriptions[irq].ipxactAbstrDef.version = "1.0";
  port_descriptions[irq].port_must_bind = 0;
  port_descriptions[irq].params_count = 3;
  port_descriptions[irq].clock = signal_clock;
  m_machineArch->configureClock(irq, mb::sysc::sc_time_to_ps(signal_clock));
  port_descriptions[irq].add_write_phase(tlm::tlm_phase(tlm::BEGIN_REQ), !0, 1);
  port_descriptions[irq].add_write_phase(tlm::tlm_phase(tlm::BEGIN_RESP), !1, 1);


  port_descriptions[master].default_read_transaction_name = "READ";
  port_descriptions[master].default_write_transaction_name = "WRITE";
  port_descriptions[irq].default_write_transaction_name = "WRITE";

  fix_internal_clock_parameter(clock, "clock");
  set_ports(mb::sysc::sc_time_to_ps(clock), port_count, port_descriptions);

  bool isCpu = false;
  
  esl::tlm_sim::UserRunningModel* userRunningModel = Papoulis_CreateUserRunningModel(name(),
                                                                                     0,
                                                                                     this,
                                                                                     simulation,
                                                                                     false,
                                                                                     isCpu);
  setUserRunningModel(userRunningModel, isCpu);
  set_nominal_voltage(nominal_voltage);
  registerParameter("clock", "sc_core::sc_time", sdGetParameterAsConstString("clock"));
  registerParameter("signal_clock", "sc_core::sc_time", sdGetParameterAsConstString("signal_clock"));
  registerParameter("axi_clock", "sc_core::sc_time", sdGetParameterAsConstString("axi_clock"));
  registerParameter("nominal_voltage", "double", sdGetParameterAsConstString("nominal_voltage"));
  registerParameter("mb_debug", "bool", sdGetParameterAsConstString("mb_debug"));
  registerParameter("verbose_parameters", "bool", sdGetParameterAsConstString("verbose_parameters"));
  registerParameter("dmi_enabled", "bool", sdGetParameterAsConstString("dmi_enabled"));
  registerParameter("warning_level", "const char*", sdGetParameterAsConstString("warning_level"));
  registerParameter("master_outstanding", "unsigned int", sdGetParameterAsConstString("master_outstanding"));
  registerParameter("master_read_data_queue_size", "unsigned int", sdGetParameterAsConstString("master_read_data_queue_size"));
  registerParameter("master_write_data_queue_size", "unsigned int", sdGetParameterAsConstString("master_write_data_queue_size"));
  registerParameter("irq_pipeline_length", "unsigned int", sdGetParameterAsConstString("irq_pipeline_length"));
  set_sync_all(0); 
  
  
  
  
  

  
  

  


  

  constant_global_power_policy* p = new constant_global_power_policy(userRunningModel);
  
  
  
  set_global_power_policy(p);
}

void driver_t_base::update_sync_all() {
  set_sync_all(0);
  
}

void driver_t_base::update_pipeline_parameters(esl::sc_sim::pipeline_policy* handle) {
  if (m_pipeline_vector.size() == 0)
    return;


}

void driver_t_base::update_sequential_parameters(esl::sc_sim::sequential_policy* handle) {
  if (m_sequential_vector.size() == 0)
    return;

}

void driver_t_base::update_delay_parameters(esl::sc_sim::delay_policy* handle) {
  if (m_delay_vector.size() == 0)
    return;

}

void driver_t_base::update_bus_parameters(esl::sc_sim::uniform_bus_policy* handle) {
  if (m_bus_vector.size() == 0)
    return;

}

void driver_t_base::update_power_parameters(esl::sc_sim::power_policy* handle) {
  if (m_power_vector.size() == 0)
    return;

}

void driver_t_base::update_state_power_parameters(esl::sc_sim::state_power_policy* handle) {
  if (m_state_power_vector.size() == 0)
    return;

}

void driver_t_base::update_global_power_parameters(esl::sc_sim::constant_global_power_policy* handle) {
  
  
  return;  
}

bool driver_t_base::triggerRegistersGotHit(unsigned portIndex, tlm::tlm_generic_payload& trans) {
  mb::utl::Segment<uint64_t> transactionRange(trans.get_address(), trans.get_address() + trans.get_data_length());

  return false;
}

bool driver_t_base::portHasRegisters(unsigned portIndex) {
  switch (portIndex) {

  }
  return false;
}



/**************************************************************/
/*                                                            */
/*      Copyright Mentor Graphics Corporation 2006 - 2012     */
/*                  All Rights Reserved                       */
/*                                                            */
/*       THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY      */
/*         INFORMATION WHICH IS THE PROPERTY OF MENTOR        */
/*         GRAPHICS CORPORATION OR ITS LICENSORS AND IS       */
/*                 SUBJECT TO LICENSE TERMS.                  */
/*                                                            */
/**************************************************************/

//*<
//* Generated By Model Builder, Mentor Graphics Computer Systems, Inc.
//*
//* This file is write protected.
//* DO NOT MODIFY THIS FILE.
//*
//* This file contains the PVT class for driver.
//* It connects between the PV and T models.
//* Your top-level design should instantiate this model.
//* 
//* In order to synchronize the activty between the PV and the T models, every 
//* PV transaction is monitored and queued in the T sync ports.
//* Whenever a synchronization point is reached, the T models are executed and 
//* the corresponding T transactions are launched.
//* A synchronization point is reached whenever there is a wait statement on a testbench thread. 
//*
//* Model Builder version: 4.1.0
//* Generated on: Jan. 27, 2016 03:09:20 PM, (user: mbradley)
//*>

#include "driver_model.h"

using namespace std;
using namespace sc_core;
using namespace sc_dt;


#include "driver_pv.h"




// Constructor
driver_pvt::driver_pvt(sc_module_name module_name)
  : esl::sc_sim::PVTBaseModel(module_name, 0),
    driver_pvt_param_defaults(this->name()),
    master("master"),
    irq("irq"), 
    master_entry("unvisible_master_entry"),
    irq_entry("unvisible_irq_entry"),
    m_master_nb_connector(*this),
    m_irq_nb_connector(*this)

{


  m_driver_t = driver_t_base::create_t("T", 1);
  m_driver_pv = new driver_pv("PV");
  bind();
}  


driver_pvt::driver_pvt(sc_module_name module_name, sc_core::sc_time clock_init, sc_core::sc_time signal_clock_init, sc_core::sc_time axi_clock_init, double nominal_voltage_init, bool mb_debug_init, bool verbose_parameters_init, bool dmi_enabled_init, const char* warning_level_init, unsigned int master_outstanding_init, unsigned int master_read_data_queue_size_init, unsigned int master_write_data_queue_size_init, unsigned int irq_pipeline_length_init)
  : esl::sc_sim::PVTBaseModel(module_name, 0),
  driver_pvt_param_defaults(this->name(), clock_init, signal_clock_init, axi_clock_init, nominal_voltage_init, mb_debug_init, verbose_parameters_init, dmi_enabled_init, warning_level_init, master_outstanding_init, master_read_data_queue_size_init, master_write_data_queue_size_init, irq_pipeline_length_init),
    master("master"),
    irq("irq"), 
    master_entry("unvisible_master_entry"),
    irq_entry("unvisible_irq_entry"),
    m_master_nb_connector(*this),
    m_irq_nb_connector(*this)
{


  m_driver_t = driver_t_base::create_t("T", 1);
  m_driver_pv = new driver_pv("PV");
  bind();
} 

driver_pvt::driver_pvt(sc_module_name module_name,  std::vector<std::pair<char*, unsigned int> > &change_parameters)
  : esl::sc_sim::PVTBaseModel(module_name, 0),
  driver_pvt_param_defaults(this->name(), change_parameters),
    master("master"),
    irq("irq"), 
    master_entry("unvisible_master_entry"),
    irq_entry("unvisible_irq_entry"),
    m_master_nb_connector(*this),
    m_irq_nb_connector(*this)
{


  m_driver_t = driver_t_base::create_t("T", 1);
  m_driver_pv = new driver_pv("PV");
  bind();
} 

driver_pvt::~driver_pvt() {
  remove_pending_scenes();
  delete m_driver_t; delete m_driver_pv;
}




void driver_pvt::bind()
{
  /* connect pv to entry ports */
  
  
  getPV()->master.bind(master_entry); 
  irq_entry(getPV()->irq);  

  /* set callbacks on external and entry ports */ 

  irq.b_transport_cb.set(this, &self_type::b_transport_inside_irq);

  master_entry.b_transport_cb.set(this, &self_type::b_transport_outside_master);
  master_entry.transport_dbg_cb.set(this, &self_type::transport_dbg_outside_master);
  master_entry.get_direct_mem_ptr_cb.set(&master, &master_type::get_direct_mem_ptr);

  
  /* connect t non blocking callbacks */

  master.nb_transport_bw_cb.set(this, &self_type::receive_nb_transport_master);
  getT()->set_port_cb(0, &m_master_nb_connector);

  irq.nb_transport_fw_cb.set(this, &self_type::receive_nb_transport_irq);
  getT()->set_port_cb(1, &m_irq_nb_connector);

  master.invalidate_direct_mem_ptr_cb.set(&master_entry, &master_entry_type::invalidate_direct_mem_ptr);

  /* check mb_event policies */
  m_driver_t->check_mb_events();
}


void driver_pvt::b_transport_inside_irq(tlm::tlm_generic_payload& p, sc_core::sc_time& t)
{
  mb::tlm20::pvt_ext* extension = mb::tlm20::setup_pvt_ext(p);
  if (extension) {
    mb::mb_module* current_model = dynamic_cast<mb::mb_module*>(m_driver_pv);
    if (current_model)
      current_model->set_current_token(extension->getToken());
  }
  irq_entry.write(*(bool*)p.get_data_ptr());
}

void driver_pvt::b_transport_outside_master(tlm::tlm_generic_payload& p, sc_core::sc_time& t)
{
  
  master.b_transport(p, t);
  
} 

unsigned int driver_pvt::transport_dbg_outside_master(tlm::tlm_generic_payload& p)
{
  
  return master.transport_dbg(p);
  
}

