
/**************************************************************/
/*                                                            */
/*      Copyright Mentor Graphics Corporation 2006 - 2012     */
/*                  All Rights Reserved                       */
/*                                                            */
/*       THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY      */
/*         INFORMATION WHICH IS THE PROPERTY OF MENTOR        */
/*         GRAPHICS CORPORATION OR ITS LICENSORS AND IS       */
/*                 SUBJECT TO LICENSE TERMS.                  */
/*                                                            */
/**************************************************************/


//*<
//* Generated By Model Builder, Mentor Graphics Computer Systems, Inc.
//*
//* This file contains the timing class for JPEG_ENCODER.
//*
//* This is a template file: You may modify this file to implement the 
//* timing behavior of your component.
//* The functions below allows advance users to customize the timing behavior of your model.
//* 
//* Model Builder version: 4.1.0
//* Generated on: Jan. 27, 2016 06:22:45 PM, (user: mbradley)
//*>


#include "JPEG_ENCODER_t.h"


#include <iostream>

using namespace std;
using namespace sc_dt;
using namespace sc_core;

JPEG_ENCODER_t_base* JPEG_ENCODER_t_base::create_t(const char* name, long simulation) {
  return new JPEG_ENCODER_t(name, simulation);
}

JPEG_ENCODER_t::JPEG_ENCODER_t(sc_module_name _name, long simulation)
  : JPEG_ENCODER_t_base(_name, simulation) {
  
}

